# Default values for bitholla-hollaex-nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
imageRegistry: bitholla/hollaex-web
dockerTag:
  
imagePullSecrets:
  - name: docker-registry-secret

envName: hollaex-web-env

stable:
  replicaCount: 1

nodeSelector: {}

autoScaling:
  hpa:
    enable: false 
    maxReplicas: 4
    cpu: 500m

podRestart_webhook_url:
  
    
  

