{{- if and (eq .Values.job.enable false) (eq .Values.cronjob.enable false) }}

kind: Service
apiVersion: v1
metadata:
  labels:
    app: {{.Release.Name}}
  name: {{.Release.Name}}
  namespace: {{.Release.Namespace}}
spec:
  type: ClusterIP
  ports:
  - name: port
    port: 10010
    targetPort: 10010
  - name: websocket-port
    port: 10080
    targetPort: 10080

  selector:
    app: {{.Release.Name}}

{{- end }}