clone:
  git:
    image: bitholla/devops-tools:drone_git-80f15d1
    when:
      branch: [ master ]

pipeline:
  ### SLACK NOTIFY - Build start ###
  notify_job_start:
    image: bitholla/devops-tools:drone_slack-8a15f61
    channel: deployment
    secrets: [ slack_webhook ]
    template: "<{{build.link}}|Deployment> - #{{build.number}} started on <https://github.com/{{repo.owner}}/{{repo.name}}/tree/{{build.branch}}|{{repo.name}} / {{build.branch}}> by {{build.author}}"
    when:
      branch: [ master ]
      event: push

  #### Filtering branches to not build it ####
  not_building_this_branch:
    image: golang:1.10.0-alpine
    commands:
      - echo "Your latest code is now up on ${DRONE_BRANCH}. but Drone will not build this branch. have fun :)"
    when:
      branch:
        exclude: [ master ]
        event: push

  #### Docker image tagging - PRODUCTION RELEASES ####
  docker_tagging:
    image: alpine
    commands:
      - export PACKAGE_VERSION="$(cat version)" && echo "$PACKAGE_VERSION" > .tags
      - echo -n ",latest" >> .tags
      - echo "Current Docker tag is :" && cat .tags
      - echo "dockerTag:$(cat .tags)" > .dockerTag.yml
    when:
      branch: [ master ]
      event: push

      
  #### Docker image build ####
  docker_build:
    #image: bitholla/devops-tools:drone_docker-1086846
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: bitholla/hex-cli
    dockerfile: docker/Dockerfile
    when:
      branch: [ master ] 
      event: push
  
  #### SLACK NOTIFY - Build status report ####
  notify_to_deployment:
    image: bitholla/devops-tools:drone_slack-8a15f61
    channel: deployment
    secrets: [ slack_webhook ]
    when:
      status: [success, failure]
      branch: [ master ]
      event: push

  
  version_tagging_for_partymaker:
    image: alpine
    commands:
      - export PACKAGE_VERSION="$(cat version)" && echo "$PACKAGE_VERSION" > .tags
    when:
      branch: [ master ]
      event: push

  #### SLACK NOTIFY - to releases channel ####
  notify_to_releases:
    image: bitholla/devops-tools:drone_partymaker-0.1.1
    #pull: true
    secrets:
      - source: slack_webhook_releases
        target: webhook_url
    when:
      status: [success]
      branch: [ master ]
      event: push