kind: pipeline
type: docker
name: docker_build_amd64

steps:

- name: notify_job_start
  image: plugins/slack
  settings:
    template: "<{{build.link}}|Docker Build for Amd64> - #{{build.number}} started on <https://github.com/{{repo.owner}}/{{repo.name}}/tree/{{build.branch}}|{{repo.name}} / {{build.branch}}> by {{build.author}}"
  channel: deployment
  environment:
    SLACK_WEBHOOK:
      from_secret: slack_webhook
  

- name: docker_tag_for_release_master
  image: alpine
  commands:
  -  export PACKAGE_VERSION="$(cat version)" && echo "$PACKAGE_VERSION" > .tags
  - echo "Current Release tag is :" && cat .tags
  when:
    branch: master

- name: create_github_release
  image: bitholla/devops-tools:drone_github_hub-2004241546
  environment:
    GITHUB_TOKEN:
      from_secret: github_oauth2_token_for_releases
  commands:
    - apt-get update && apt-get install -y hub git
    - hub release create -m "HollaEx CLI v$(cat .tags) Release" -t ${DRONE_BRANCH} $(cat .tags)
  when:
    branch: master

- name: notify_job_done
  image: bitholla/devops-tools:drone_slack-8a15f61
  channel: deployment
  environment:
    SLACK_WEBHOOK:
      from_secret: slack_webhook
  when:
    status: [ success, failure ]

- name: notify_to_releases
  image: bitholla/devops-tools:drone_partymaker-0.1.4
  channel: deployment
  environment:
    WEBHOOK_URL:
      from_secret: webhook_url
  when:
    status: [ success, failure ]

- name: notify_to_discord_releases
  image: bitholla/devops-tools:drone_partymaker-0.1.5
  channel: deployment
  settings:
    target: discord
    release_name: hollaex-cli
  environment:
    WEBHOOK_URL:
      from_secret: discord_webhook_url
  when:
    status: [ success, failure ]
    branch: master
  
trigger:
  branch: 
    - master
    - testnet
  event:
    - push

