kind: pipeline
type: docker
name: docker_build_amd64

steps:

- name: notify_job_start
  image: plugins/slack
  settings:
    template: "<{{build.link}}|Docker Build for Amd64> - #{{build.number}} started on <https://github.com/{{repo.owner}}/{{repo.name}}/tree/{{build.branch}}|{{repo.name}} / {{build.branch}}> by {{build.author}}"
  channel: deployment
  environment:
    SLACK_WEBHOOK:
      from_secret: slack_webhook
  
- name: docker_tagging
  image: alpine
  commands: 
    - export PACKAGE_VERSION="$(cat version)" && echo "$PACKAGE_VERSION,$PACKAGE_VERSION-amd64" > .tags 
    - echo "Current Docker tag is :" && cat .tags
    - echo "dockerTag:$(cat .tags)" > .dockerTag.yml

- name: docker_build
  image: plugins/docker
  settings:
    dockerfile: docker/Dockerfile
    repo: bitholla/hollaex-cli
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password

- name: notify_job_done
  image: bitholla/devops-tools:drone_slack-8a15f61
  channel: deployment
  environment:
    SLACK_WEBHOOK:
      from_secret: slack_webhook
  when:
    status: [ success, failure ]

- name: partymaker_version_tagging
  image: alpine
  commands: 
    - export PACKAGE_VERSION="$(cat version)" && echo "$PACKAGE_VERSION" > .tags

- name: notify_to_releases
  image: bitholla/devops-tools:drone_partymaker-0.1.4
  channel: deployment
  environment:
    WEBHOOK_URL:
      from_secret: webhook_url
  when:
    status: [ success, failure ]
  
trigger:
  branch: 
    - master
  event:
    - push

---

kind: pipeline
type: docker
name: docker_build_arm64v8

steps:

- name: notify_job_start
  image: plugins/slack
  settings:
    template: "<{{build.link}}|Docker Build for Arm64v8> - #{{build.number}} started on <https://github.com/{{repo.owner}}/{{repo.name}}/tree/{{build.branch}}|{{repo.name}} / {{build.branch}}> by {{build.author}}"
  channel: deployment
  environment:
    SLACK_WEBHOOK:
      from_secret: slack_webhook
  
- name: docker_tagging
  image: alpine
  commands: 
    - export PACKAGE_VERSION="$(cat version)" && echo "$PACKAGE_VERSION-arm64v8" > .tags
    - echo "Current Docker tag is :" && cat .tags
    - echo "dockerTag:$(cat .tags)" > .dockerTag.yml

- name: docker_build
  image: plugins/docker
  settings:
    dockerfile: docker/Dockerfile.arm64v8
    repo: bitholla/hollaex-cli
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password

- name: notify_job_done
  image: bitholla/devops-tools:drone_slack-8a15f61
  channel: deployment
  environment:
    SLACK_WEBHOOK:
      from_secret: slack_webhook
  when:
    status: [ success, failure ]
  
trigger:
  branch: 
    - master
  event:
    - push

---

kind: pipeline
type: docker
name: docker_manifest_create

depends_on:
  - docker_build_amd64
  - docker_build_arm64v8

steps:
- name: notify_job_start
  image: plugins/slack
  settings:
    template: "<{{build.link}}|Docker Multiarch Manifest Creation> - #{{build.number}} started on <https://github.com/{{repo.owner}}/{{repo.name}}/tree/{{build.branch}}|{{repo.name}} / {{build.branch}}> by {{build.author}}"
  channel: deployment
  environment:
    SLACK_WEBHOOK:
      from_secret: slack_webhook

- name: manifest
  image: docker:dind
  privileged: true
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  volumes:
    - name: docker
      path: /var/run/docker.sock
  commands:
    - docker login -u $${DOCKER_USERNAME} -p $${DOCKER_PASSWORD}
    - export DOCKER_CLI_EXPERIMENTAL=enabled
    - docker manifest create bitholla/hollaex-cli:$(cat version) bitholla/hollaex-cli:$(cat version)-amd64 bitholla/hollaex-cli:$(cat version)-arm64v8 --amend
    - docker manifest annotate bitholla/hollaex-cli:$(cat version) bitholla/hollaex-cli:$(cat version)-amd64 --arch amd64
    - docker manifest annotate bitholla/hollaex-cli:$(cat version) bitholla/hollaex-cli:$(cat version)-arm64v8 --arch arm64
    - docker manifest push bitholla/hollaex-cli:$(cat version)
    - docker manifest create bitholla/hollaex-cli:latest bitholla/hollaex-cli:$(cat version)-amd64 bitholla/hollaex-cli:$(cat version)-arm64v8 --amend
    - docker manifest annotate bitholla/hollaex-cli:latest bitholla/hollaex-cli:$(cat version)-amd64 --arch amd64
    - docker manifest annotate bitholla/hollaex-cli:latest bitholla/hollaex-cli:$(cat version)-arm64v8 --arch arm64
    - docker manifest push bitholla/hollaex-cli:latest


- name: notify_job_done
  image: bitholla/devops-tools:drone_slack-8a15f61
  channel: deployment
  environment:
    SLACK_WEBHOOK:
      from_secret: slack_webhook
  when:
    status: [ success, failure ]
    
volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

trigger:
  branch: 
    - master
  event:
    - push