kind: pipeline
type: docker
name: amd64

platform:
  arch: amd64
  os: linux

steps:

- name: notify_job_start
  image: plugins/slack
  settings:
    template: "<{{build.link}}|Deployment> - #{{build.number}} for AMD64 Arch  started on <https://github.com/{{repo.owner}}/{{repo.name}}/tree/{{build.branch}}|{{repo.name}} / {{build.branch}}> by {{build.author}}"
  channel: deployment
  environment:
    SLACK_WEBHOOK:
      from_secret: slack_webhook
  
- name: docker_tagging
  image: alpine
  commands: 
    - export PACKAGE_VERSION="$(cat version)" && echo "$PACKAGE_VERSION" > .tags
    - echo -n ",latest" >> .tags
    - echo "Current Docker tag is :" && cat .tags
    - echo "dockerTag:$(cat .tags)" > .dockerTag.yml

- name: docker_build
  image: plugins/docker
  settings:
    dockerfile: docker/Dockerfile.arm64
    repo: bitholla/hollaex-cli
    tag: test-arm64
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password

- name: notify_job_done
  image: bitholla/devops-tools:drone_slack-8a15f61
  channel: deployment
  environment:
    SLACK_WEBHOOK:
      from_secret: slack_webhook
  when:
    status: [ success, failure ]

- name: partymaker_version_tagging
  image: alpine
  commands: 
    - export PACKAGE_VERSION="$(cat version)" && echo "$PACKAGE_VERSION" > .tags

- name: notify_to_releases
  image: bitholla/devops-tools:drone_partymaker-0.1.1
  channel: deployment
  environment:
    WEBHOOK_URL:
      from_secret: webhook_url
  when:
    status: [ success, failure ]
  
trigger:
  branch: 
    - master
  event:
    - push

---

kind: pipeline
type: docker
name: arm64

steps:
# - name: notify_job_start
#   image: plugins/slack
#   template: "<{{build.link}}|Deployment> - #{{build.number}} for ARM64 Arch started on <https://github.com/{{repo.owner}}/{{repo.name}}/tree/{{build.branch}}|{{repo.name}} / {{build.branch}}> by {{build.author}}"
#   channel: deployment
#   environment:
#     SLACK_WEBHOOK:
#       from_secret: slack_webhook

- name: qemu_user_static
  image: ubuntu:18.04
  commands: 
    - apt-get update && apt-get install -y qemu-user
    - mkdir /drone/src/docker/qemu
    - mv /usr/bin/qemu-s390x /usr/bin/qemu-arm /usr/bin/qemu-aarch64 /drone/src/docker/qemu

- name: docker_build
  image: plugins/docker
  settings:
    dockerfile: docker/Dockerfile.s390x
    repo: bitholla/hollaex-cli
    tag: arm64-test
  environment:
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
  
# - name: notify_job_done
#   image: bitholla/devops-tools:drone_slack-8a15f61
#   channel: deployment
#   environment:
#     SLACK_WEBHOOK:
#       from_secret: slack_webhook
  when:
    status: [ success, failure ]

trigger:
  branch: 
    - develop
  event:
    - push
