# Default values for bitholla-hollaex-nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
imageRegistry: bitholla/hollaex
dockerTag:
  
imagePullSecrets:
  - name: bitholla-registry-secret

envName: hollaex-testnet-env
secretName: hollaex-testnet-secret

DEPLOYMENT_MODE: api
PAIR:

stable:
  replicaCount: 1
  
staging:
  enable: false
  replicaCount: 1
  dockerTag:

nodeSelector: {}

autoScaling:
  hpa:
    enable: false 
    maxReplicas: 4
    cpu: 500m

APM_URL:

podRestart_webhook_url:


job:
  enable: false
  mode: #add_coin
        #remove_coin
        #add_pair
        #remove_pair
  env:
    coin_symbol:
    pair_name:
  
    
  

